export const ADD_USER = 'ADD_USER'; // Action to add the user to the database

const id = 1; // This is the id that will be generated by the database when the user is registered

export function addUser(firstName,lastName,email,phone,role,state,password){ // User is added to the redux store
    return({
        type: ADD_USER,
        id: id,
        firstName,
        lastName,
        email,
        phone,
        role,
        state,
        password
    });
}